version: '3'
services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec foreman start"
    links:
      - db
    volumes:
      - .:/rails_bbs
      - bundle:/bundle
    ports:
      - "3000:3000"
      - "3035:3035"
volumes:
  bundle:
    driver: local
  db-data:
    driver: local

